server:
  port: 52345

spring:
  datasource:
    url: jdbc:h2:file:./data/prod-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # Choose "update", "validate", or "none" for production (consider "none" if schema changes are managed by Flyway)
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration  # Ensure migrations are properly located
  sql:
    init:
      platform: h2  # Ensures the correct database platform is used

logging:
  level:
    root: WARN
    org.springframework: ERROR
